version: '3.9'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    command: sh -c "alembic upgrade head && uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DB_HOST=db
      - CACHE_HOST=cache
      - DEBUG=true
    depends_on:
      - db
      - cache
  
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev

  cache:
    image: redis:7-alpine
    ports:
      - 6379:6379
volumes:
  pg_data:
