"""update user age field type

Revision ID: b38a8adff8bb
Revises: 6cf5ecbfc535
Create Date: 2023-07-03 07:05:36.544943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38a8adff8bb'
down_revision = '6cf5ecbfc535'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'age',
                    existing_type=sa.String(),
                    type_=sa.Integer(),
                    existing_nullable=True,
                    postgresql_using="age::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'age',
                    existing_type=sa.Integer(),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###
